---
# tasks file for ssh
- name: Criando usuarios SSH
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    shell: /bin/bash
    password: "{{ item.password }}"
  with_items: "{{ users_ssh }}"
  no_log: true

- name: Copiando arquivo de configuração do SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify: restart ssh

- name: Criando diretório .ssh para usuário deploy
  file:
    owner: "{{ user_deploy }}"
    group: "{{ user_deploy }}"
    path: "/home/{{ user_deploy }}/.ssh"
    state: directory
    mode: '0755'

- name: Gerando chave ssh para o usuario
  openssh_keypair:
    owner: "{{ user_deploy }}"
    group: "{{ user_deploy }}"
    path: "/home/{{ user_deploy }}/.ssh/id_rsa"
    comment: "{{ user_deploy }}"
    size: 2048